### Задание 1

In [5]:
import numpy as np

In [18]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [19]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [65]:
mean_a = np.array([np.mean(a[:,0]), np.mean(a[:,1])])

In [66]:
mean_a

array([2. , 8.4])

### Задание 2

In [88]:
a_centered = np.array([a[:,0] - mean_a[0], a[:,1] - mean_a[1]]).transpose()

In [89]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [105]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1] / (np.sum(a[:,1]) - 1)

In [106]:
a_centered_sp

0.1951219512195122